---
name: SVN-Log-Index
version: 0.40
author:
  - 'The current maintainer is Nik Clayton, <nikc@cpan.org>.'
  - 'The original author was Garrett Rooney, <rooneg@electricjellyfish.net>'
abstract: Index and search over Subversion commit logs.
license: perl
requires:
  Plucene: 1
  SVN::Log: 0.03
  YAML: 0
recommends:
  SVN::Core: 0
provides:
  SVN::Log::Index:
    file: lib/SVN/Log/Index.pm
    version: 0.40
generated_by: Module::Build version 0.2611
