--- #YAML:1.0
name: SVN-Log-Index
version: 0.20
license: perl
distribution_type: module
requires:
  Plucene: 1
recommends:
  SVN::Core: 0
build_requires: {}
conflicts: {}
provides:
  SVN::Log::Index:
    file: lib/SVN/Log/Index.pm
    version: 0.20
generated_by: Module::Build version 0.21
