--- #YAML:1.0
name: SVN-Log-Index
version: 0.1
license: perl
distribution_type: module
requires:
  PLucene: 1
  SVN::Core: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  SVN::Log::Index:
    file: lib/SVN/Log/Index.pm
    version: 0.1
generated_by: Module::Build version 0.21
